server:
  port: 9002
spring:
  application:
    name: micservice-movie
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳
micservice-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule