server:
  port: 9101
spring:
  application:
    name: micservice-user
  datasource:
    url: jdbc:mysql://192.168.66.136:3306/movie?characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳